version: "3.3"

services:
  pg_db:
    image: postgres:latest
    container_name: pg_db
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_ui:
    image: adminer:latest
    container_name: db_ui
    ports:
      - "8099:8080"

  # IN PRODUCTION use gunicorn
  # gunicorn app.wsgi:application --bind 0.0.0.0:8000
  app:
    build: .
    container_name: app
    command: >
      sh -c "pip3 install -r requirements.txt &&
             pip3 install -r requirements-dev.txt &&
             cd app && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:8000"

volumes:
  postgres_data:
