[tool.isort]
line_length = 120
use_parentheses = true
skip = "migrations,venv"
profile = "black"

[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
  | venv
)/
'''

[tool.flake8]
max-line-length = 120
# ignore = ["F811", "F401", "W503", "N805", "E203"]
exclude = [".git", "__pycache__", "venv", "migrations"]
