# Generated by Django 3.2.23 on 2024-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('trim', models.CharField(max_length=255)),
                ('dealer_name', models.CharField(max_length=255)),
                ('dealer_street', models.CharField(max_length=255)),
                ('dealer_city', models.CharField(max_length=255)),
                ('dealer_state', models.CharField(max_length=255)),
                ('dealer_zip', models.CharField(max_length=5)),
                ('listing_price', models.CharField(max_length=255)),
                ('listing_mileage', models.IntegerField()),
                ('used', models.BooleanField(default=True)),
                ('certified', models.BooleanField(default=False)),
                ('style', models.CharField(max_length=255)),
                ('driven_wheels', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('seller_website', models.CharField(max_length=255)),
                ('last_seen_date', models.DateField(null=True)),
                ('first_seen_date', models.DateField(null=True)),
                ('dealer_vdp_last_seen_date', models.DateField(null=True)),
                ('listing_status', models.CharField(max_length=50)),
            ],
        ),
    ]
