# Generated by Django 3.2.23 on 2024-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='dealer_vdp_last_seen_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
