# Generated by Django 3.2.23 on 2024-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(max_length=255),
        ),
    ]
