# Generated by Django 3.2.23 on 2024-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_interior_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driven_wheels',
            field=models.CharField(max_length=255),
        ),
    ]
