# Generated by Django 3.2.23 on 2024-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_dealer_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='exterior_color',
            field=models.CharField(max_length=255),
        ),
    ]
