# Generated by Django 3.2.23 on 2024-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_ve_vin_d8dea1_idx'),
        ),
    ]
