# Generated by Django 3.2.23 on 2024-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_vehicles_ve_vin_d8dea1_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_vin_d8dea1_idx',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vin_idx'),
        ),
    ]
