# Generated by Django 3.2.25 on 2024-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_auto_20240124_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='listing_mileage',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='listing_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
